// Generates the document pages that share the site chrome:
//   - the Ask FrontDesk hub (ask-frontdesk.html) and one page per article
//     (ask/<slug>.html) from content/articles.json — the same file the Ask FrontDesk
//     Assistant reads, so the site and the chat never disagree
//   - the About page (about.html), final copy from spec §13
//
//   npm run build:pages
import { readFileSync, writeFileSync, mkdirSync, readdirSync, unlinkSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const { pillars, articles } = JSON.parse(readFileSync(join(root, 'content/articles.json'), 'utf8'));

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const minutes = (a) => Math.max(1, Math.ceil(a.paragraphs.join(" ").split(/\s+/).length / 220));
const pillarOf = (id) => pillars.find((p) => p.id === id) || pillars[pillars.length - 1];

const symbols = `<svg width="0" height="0" style="position:absolute" aria-hidden="true" focusable="false">
    <symbol id="fd-mark" viewBox="0 0 61 43">
      <path fill="currentColor" d="M1 2h42a16.5 19.25 0 0 1 0 38.5H22v-8h21a8 11.25 0 0 0 0-22.5H1z"/>
      <path fill="currentColor" d="M1 17.5h33v8H9.5v15H1z"/>
    </symbol>
    <symbol id="i-arrow" viewBox="0 0 24 24">
      <path fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" d="M4 12h15m-6-6 6 6-6 6"/>
    </symbol>
  </svg>`;

function page({ base, title, description, current, body }) {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(description)}">
  <meta name="theme-color" content="#ffffff">
  <link rel="icon" href="${base}assets/img/mark.svg" type="image/svg+xml">
  <link rel="preload" as="font" type="font/woff2" href="${base}assets/fonts/archivo-latin.woff2" crossorigin>
  <link rel="preload" as="font" type="font/woff2" href="${base}assets/fonts/montserrat-latin.woff2" crossorigin>
  <link rel="stylesheet" href="${base}assets/css/styles.css">
  <script>document.documentElement.classList.add('js');</script>
  <script src="${base}assets/js/config.js" defer></script>
  <script src="${base}assets/js/main.js" defer></script>
  <script src="${base}assets/js/ask.js" defer></script>
</head>
<body class="is-subpage">
  <!-- Generated by scripts/build-pages.mjs. Edit the script or content/, not this file. -->
  ${symbols}

  <a class="skip" href="#main">Skip to content</a>

  <header class="topbar">
    <div class="pill pill--brand">
      <a class="brand" href="${base}index.html" aria-label="FrontDesk JA — home">
        <svg class="brand__mark" aria-hidden="true"><use href="#fd-mark"/></svg>
        <span class="brand__text">
          <span class="brand__word"><b>FRONT</b>DESK<small>JA</small></span>
          <span class="brand__tag">Empowering the world with AI.</span>
        </span>
      </a>
      <button class="burger" type="button" aria-expanded="false" aria-controls="menu" aria-label="Open menu">
        <span></span><span></span><span></span>
      </button>
    </div>
    <div class="pill pill--actions">
      <a class="btn btn--sm" href="${base}pricing.html">Get Started <svg aria-hidden="true"><use href="#i-arrow"/></svg></a>
    </div>
  </header>

  <div class="menu" id="menu" hidden>
    <nav class="menu__nav" aria-label="Main">
      <ol class="menu__list">
        <li><a class="menu__link" href="${base}index.html">Home</a></li>
        <li class="menu__group">
          <span class="menu__label">Services</span>
          <ul class="menu__sub">
            <li><a href="${base}index.html#aeo"><span>AEO</span><em>Be found</em></a></li>
            <li><a href="${base}index.html#assistant"><span>Assistant</span><em>Be available</em></a></li>
            <li><a href="${base}index.html#receptionist"><span>Receptionist</span><em>No hold time</em></a></li>
          </ul>
        </li>
        <li><a class="menu__link" href="${base}pricing.html">Pricing</a></li>
        <li><a class="menu__link" href="${base}ask-frontdesk.html"${current === 'hub' ? ' aria-current="page"' : ''}>Ask FrontDesk</a></li>
        <li><a class="menu__link" href="${base}about.html"${current === 'about' ? ' aria-current="page"' : ''}>About</a></li>
      </ol>
    </nav>
    <div class="menu__foot">
      <a class="btn" href="${base}pricing.html">Get Started <svg aria-hidden="true"><use href="#i-arrow"/></svg></a>
      <p>The front desk of the future.</p>
    </div>
  </div>

${body}

  <footer class="footer">
    <div class="footer__grid">
      <div class="footer__brand">
        <svg class="brand__mark" aria-hidden="true"><use href="#fd-mark"/></svg>
        <span class="brand__text">
          <span class="brand__word"><b>FRONT</b>DESK<small>JA</small></span>
          <span class="brand__tag">Empowering the world with AI.</span>
        </span>
      </div>
      <nav class="footer__nav" aria-label="Footer">
        <a href="${base}index.html">Home</a>
        <a href="${base}index.html#aeo">AEO</a>
        <a href="${base}index.html#assistant">Assistant</a>
        <a href="${base}index.html#receptionist">Receptionist</a>
        <a href="${base}pricing.html">Pricing</a>
        <a href="${base}ask-frontdesk.html">Ask FrontDesk</a>
        <a href="${base}about.html">About</a>
      </nav>
      <p class="footer__small">© <span data-year>2026</span> FrontDesk JA. The front desk of the future.</p>
    </div>
  </footer>
</body>
</html>
`;
}

function card(a, base) {
  const p = pillarOf(a.pillar);
  return `        <li>
          <a class="article-card lift" href="${base}ask/${a.slug}.html" data-pillar="${p.id}">
            <span class="article-card__meta"><i class="dot"></i>${esc(a.category)} · ${minutes(a)} min read</span>
            <span class="article-card__title">${esc(a.title)}</span>
            <span class="article-card__summary">${esc(a.summary)}</span>
            <span class="article-card__go">Read <svg aria-hidden="true"><use href="#i-arrow"/></svg></span>
          </a>
        </li>`;
}

/* ---------- hub ---------- */
const sections = pillars
  .map((p) => ({ p, list: articles.filter((a) => a.pillar === p.id) }))
  .filter((s) => s.list.length)
  .map(({ p, list }) => `    <section class="hub__group" data-pillar="${p.id}" aria-labelledby="g-${p.id}">
      <header class="hub__group-head">
        <p class="eyebrow">${esc(p.name)} — ${esc(p.tagline)}</p>
        <p class="hub__group-intro" id="g-${p.id}">${esc(p.intro)}</p>
      </header>
      <ul class="hub__list">
${list.map((a) => card(a, '')).join('\n')}
      </ul>
    </section>`).join('\n\n');

const hub = page({
  base: '',
  title: 'Ask FrontDesk — FrontDesk JA',
  description: 'Clear answers about AI and running a business: AEO and AI search, digital front desks, missed calls and AI receptionists.',
  current: 'hub',
  body: `  <main id="main" class="hub">
    <section class="hub__intro is-in" data-page aria-labelledby="h-hub">
      <p class="eyebrow r">Ask FrontDesk</p>
      <h1 class="headline headline--wide" id="h-hub">
        <span class="ln"><span>Ask FrontDesk.</span></span>
        <span class="ln ln--light"><span>Answers about AI and business.</span></span>
      </h1>
      <p class="body r">Real questions business owners ask about AI search, digital front desks and missed calls, answered in plain language and organized by topic.</p>
      <p class="r"><button class="btn btn--ghost" type="button" data-ask>Ask your own question <svg aria-hidden="true"><use href="#i-arrow"/></svg></button></p>
    </section>

${sections}
  </main>`
});
writeFileSync(join(root, 'ask-frontdesk.html'), hub);

/* ---------- articles ---------- */
mkdirSync(join(root, 'ask'), { recursive: true });
for (const f of readdirSync(join(root, 'ask'))) if (f.endsWith('.html')) unlinkSync(join(root, 'ask', f));

for (const a of articles) {
  const p = pillarOf(a.pillar);
  const related = articles.filter((x) => x.slug !== a.slug)
    .sort((x, y) => (y.pillar === a.pillar) - (x.pillar === a.pillar)).slice(0, 2);
  const html = page({
    base: '../',
    title: `${a.title} — Ask FrontDesk`,
    description: a.summary,
    current: 'article',
    body: `  <main id="main" class="article" data-pillar="${p.id}">
    <article>
      <header class="article__head">
        <nav class="article__crumbs" aria-label="Breadcrumb"><a href="../ask-frontdesk.html">Ask FrontDesk</a><span aria-hidden="true">/</span><span>${esc(p.name)}</span></nav>
        <h1 class="article__title">${esc(a.title)}</h1>
        <p class="article__meta"><i class="dot"></i>${esc(a.category)} · ${minutes(a)} min read</p>
      </header>
      <div class="article__body">
${a.paragraphs.map((t) => `        <p>${esc(t)}</p>`).join('\n')}
      </div>
    </article>

    <aside class="article__ask" aria-label="Ask about this">
      <p class="article__ask-title">Have a question about your business?</p>
      <p>Ask FrontDesk’s own Assistant. It answers from articles like this one and from what FrontDesk offers.</p>
      <button class="btn" type="button" data-ask data-ask-question="${esc(`I just read “${a.title}”. How does this apply to my business?`)}">Ask about this <svg aria-hidden="true"><use href="#i-arrow"/></svg></button>
    </aside>

    <section class="article__related" aria-labelledby="related">
      <p class="eyebrow" id="related">Keep reading</p>
      <ul class="hub__list">
${related.map((r) => card(r, '../')).join('\n')}
      </ul>
    </section>
  </main>`
  });
  writeFileSync(join(root, 'ask', `${a.slug}.html`), html);
}

/* ---------- about (final copy, spec §13) ---------- */
const about = page({
  base: '',
  title: 'About — FrontDesk JA',
  description: 'FrontDesk JA is a technology company building AI-powered capabilities that help businesses handle the work that happens before, between, and around the job.',
  current: 'about',
  body: `  <main id="main" class="about">
    <section class="about__intro is-in" data-page aria-labelledby="h-about">
      <p class="eyebrow r">About FrontDesk JA</p>
      <h1 class="headline headline--wide" id="h-about">
        <span class="ln"><span>We’re building</span></span>
        <span class="ln"><span>the front desk</span></span>
        <span class="ln"><span>of the future.</span></span>
      </h1>
      <p class="about__lede r">FrontDesk JA is a technology company building AI-powered capabilities that help businesses handle the work that happens before, between, and around the job.</p>
    </section>

    <section class="about__belief" aria-label="What we believe">
      <p>We believe the modern front desk is no longer limited to a person sitting behind a desk or answering a phone. It is the system that helps a business get discovered, stay available, respond to customers, and move conversations toward real work.</p>
    </section>

    <section class="about__pillars" aria-labelledby="pillars-intro">
      <p class="eyebrow" id="pillars-intro">That is why FrontDesk is built around three fundamental capabilities:</p>
      <ol class="about__three">
        <li><a class="about__pillar lift" href="index.html#aeo"><h2>Be found.</h2><p>Help your business become easier for modern search and AI systems to understand and discover.</p></a></li>
        <li><a class="about__pillar lift" href="index.html#assistant"><h2>Be available.</h2><p>Give customers a digital front desk that can answer questions, understand requests, assist with bookings, and know when a real person should step in.</p></a></li>
        <li><a class="about__pillar lift" href="index.html#receptionist"><h2>Get the work.</h2><p>Give your business an AI voice front desk that can handle customer conversations without putting people on hold or making them wait for a response.</p></a></li>
      </ol>
    </section>

    <section class="about__layer" aria-label="How it fits together">
      <p>Our first layer is AEO — AI and search visibility optimization. Before a customer can contact a business, they have to find it. FrontDesk helps businesses build a clearer, more useful digital presence so modern search and AI-powered discovery systems can better understand who they are, what they do, where they operate, and when they are relevant.</p>
      <p>From there, FrontDesk helps businesses stay available when customers reach out — through digital conversations, bookings, and voice.</p>
    </section>

    <section class="about__manifesto" aria-label="Why we build">
      <p class="about__big">We are not building AI for the sake of adding AI to a business.</p>
      <p class="about__big">We are building technology that takes useful work off the business owner’s plate.</p>
      <ul class="about__less">
        <li>Less time answering the same questions.</li>
        <li>Less time managing repetitive front-desk tasks.</li>
        <li>Less time worrying about whether customers can find or reach the business.</li>
      </ul>
      <p class="about__more">More time doing the work that actually moves the business forward.</p>
    </section>

    <section class="about__close" aria-label="FrontDesk JA">
      <p class="about__sign">FrontDesk JA</p>
      <p class="about__tag"><span>Be found.</span> <span>Be available.</span> <span>Get the work.</span></p>
      <a class="btn" href="pricing.html">Get Started <svg aria-hidden="true"><use href="#i-arrow"/></svg></a>
    </section>
  </main>`
});
writeFileSync(join(root, 'about.html'), about);

console.log(`Built ask-frontdesk.html, ${articles.length} article pages and about.html.`);
